name: workspace

packages:
  - packages/**

scripts:
  gen:goldens:
    exec: flutter test --update-goldens --tags=golden
    description: Generate goldens.
    packageFilters:
      dependsOn:
        - adaptive_test_extended

  tests:
    exec: flutter test
    description: Run tests.
    packageFilters:
      dependsOn:
        - flutter_test
