name: workspace

packages:
  - packages/**

scripts:
  gen:goldens:
    exec: flutter test --update-goldens --tags=golden
    description: Generate goldens.
    packageFilters:
      dependsOn:
        - adaptive_test_extended

  tests:
    exec: flutter test --no-pub --test-randomize-ordering-seed random
    description: Run tests.
    packageFilters:
      dirExists:
        - test

  l10n:gen:
    run: melos exec --fail-fast --depends-on="intl_utils" -- dart run intl_utils:generate
    description: Generates the localization code for the main application.

  format:
    exec: dart format --set-exit-if-changed lib test
    description: Format code.

  analyze:
    exec: flutter analyze lib test
    description: Analyze code.
    packageFilters:
      dirExists:
        - test