import 'package:adaptive_test/src/adaptive/window_config.dart';
import 'package:adaptive_test/src/adaptive/window_config_data/window_config_data.dart';
import 'package:adaptive_test/src/helpers/missing_fonts.dart';
import 'package:flutter/material.dart';

/// Singleton class that configures global variables for the test.
///
/// Notably:
/// * `enforcedTestPlatform`, see [TargetPlatform].
/// * `deviceVariant`, see [WindowVariant] and [WindowConfigData].
///
/// Configure those variables in the [testExecutable] function inside the
/// `flutter_test_config.dart` file.
///
/// See: https://api.flutter.dev/flutter/flutter_test/flutter_test-library.html
class AdaptiveTestConfiguration {
  AdaptiveTestConfiguration._privateConstructor();

  static final AdaptiveTestConfiguration instance =
      AdaptiveTestConfiguration._privateConstructor();

  TargetPlatform? _enforcedTestPlatform;

  TargetPlatform? get enforcedTestPlatform => _enforcedTestPlatform;

  /// Images generated by golden test can have slight differences between the
  /// tests runtime platforms. Use this to enforce a specific platform across
  /// your team.
  ///
  /// Eg [TargetPlatform.linux], [TargetPlatform.macOS],
  /// [TargetPlatform.windows].
  void setEnforcedTestPlatform(TargetPlatform enforcedTestPlatform) {
    _enforcedTestPlatform = enforcedTestPlatform;
  }

  bool _failTestOnWrongPlatform = true;

  bool get failTestOnWrongPlatform => _failTestOnWrongPlatform;

  /// When using [enforcedTestPlatform], the default behavior is that the test
  /// will fail if the runtime platform the test is running on does not match
  /// the [enforcedTestPlatform].
  ///
  /// Setting [failTestOnWrongPlatform] to false will skip the test instead of
  /// failing it.
  void setFailTestOnWrongPlatform(bool failTestOnWrongPlatform) {
    _failTestOnWrongPlatform = failTestOnWrongPlatform;
  }

  bool _loadPlatformFallbackFonts = true;

  bool get loadPlatformFallbackFonts => _loadPlatformFallbackFonts;

  /// Whether [loadFonts] also registers the font families the framework falls
  /// back to on each platform, e.g. `Roboto` or `CupertinoSystemText`. They are
  /// not declared in any `pubspec.yaml`, so without this the text using them
  /// renders as placeholder blocks in goldens.
  ///
  /// Defaults to true. Set it to false to keep the previous behavior, for
  /// instance if you would rather register those families yourself.
  void setLoadPlatformFallbackFonts(bool loadPlatformFallbackFonts) {
    _loadPlatformFallbackFonts = loadPlatformFallbackFonts;
  }

  final Set<String> _loadedFontFamilies = {};

  /// The font families [loadFonts] registered in this test isolate.
  Set<String> get loadedFontFamilies => Set.unmodifiable(_loadedFontFamilies);

  /// Records the families [loadFonts] registered, so that [expectGolden] can
  /// tell whether the text it snapshots will render real glyphs.
  void addLoadedFontFamilies(Iterable<String> families) {
    _loadedFontFamilies.addAll(families);
  }

  final Set<String> _warnedFontFamilies = {};

  /// The missing font families [expectGolden] already warned about, see
  /// [MissingFontsBehavior.warn].
  Set<String> get warnedFontFamilies => Set.unmodifiable(_warnedFontFamilies);

  /// Records the families that were warned about, so that a gap shared by many
  /// goldens is only reported once.
  void addWarnedFontFamilies(Iterable<String> families) {
    _warnedFontFamilies.addAll(families);
  }

  MissingFontsBehavior _missingFontsBehavior = MissingFontsBehavior.warn;

  MissingFontsBehavior get missingFontsBehavior => _missingFontsBehavior;

  /// What [expectGolden] does when the widget tree asks for a font family that
  /// no font has been registered for, see [MissingFontsBehavior].
  ///
  /// Defaults to [MissingFontsBehavior.warn].
  void setMissingFontsBehavior(MissingFontsBehavior missingFontsBehavior) {
    _missingFontsBehavior = missingFontsBehavior;
  }

  WindowVariant? _deviceVariant;

  WindowVariant get deviceVariant {
    final scopedDeviceVariant = _deviceVariant;
    if (scopedDeviceVariant == null) {
      throw Exception(
        '''
Device variant is not set.
please set it first in the [testExecutable] method.
See: https://api.flutter.dev/flutter/flutter_test/flutter_test-library.html
''',
      );
    }

    return scopedDeviceVariant;
  }

  /// Set the devices variant on which you want your test to run.
  ///
  /// Eg [iPhone8], [iPhone13], [iPhone16],[iPhone16Dark], [iPadPro], [desktop], [pixel5], [pixel9].
  void setDeviceVariants(Set<WindowConfigData> deviceConfigs) {
    _deviceVariant = WindowVariant(deviceConfigs);
  }
}
