name: simple_app_example
description: A simple Flutter app to illustrate the package adaptive_test.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: any
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  adaptive_test_extended:
    path: ../../
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/dash.png
  fonts:
  - family: Roboto
    fonts:
      - asset: fonts/Roboto-Black.ttf
      - asset: fonts/Roboto-BlackItalic.ttf
      - asset: fonts/Roboto-Bold.ttf
      - asset: fonts/Roboto-BoldItalic.ttf
      - asset: fonts/Roboto-Italic.ttf
      - asset: fonts/Roboto-Light.ttf
      - asset: fonts/Roboto-LightItalic.ttf
      - asset: fonts/Roboto-Medium.ttf
      - asset: fonts/Roboto-MediumItalic.ttf
      - asset: fonts/Roboto-Regular.ttf
      - asset: fonts/Roboto-Thin.ttf
      - asset: fonts/Roboto-ThinItalic.ttf

  - family: Dubai
    fonts:
      - asset: fonts/Dubai-Bold.ttf
      - asset: fonts/Dubai-Light.ttf
      - asset: fonts/Dubai-Medium.ttf
      - asset: fonts/Dubai-Regular.ttf

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en