name: Format and test on push
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - dir: example/simple_app
            name: simple_app
          - dir: example/multi_packages_app/app
            name: multi_packages_app_app
          - dir: example/multi_packages_app/theme
            name: multi_packages_app_theme
    defaults:
      run:
        working-directory: ${{ matrix.dir }}

    steps:
      - uses: actions/checkout@v2

      - id: dotenv
        uses: falti/dotenv-action@v0.2.8
        with:
          path: .github/workflows/.env

      - uses: subosito/flutter-action@v2.5.0
        with:
          flutter-version: ${{ steps.dotenv.outputs.flutter_version }}
          channel: "stable"
          cache: true
          cache-key: flutter-macos-${{ steps.dotenv.outputs.flutter_version }}
          cache-path: ${{ runner.tool_cache }}/flutter-${{ steps.dotenv.outputs.flutter_version }}

      - name: Install Dependencies
        run: flutter packages get

      - name: Format
        run: dart format --set-exit-if-changed lib test

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: flutter test --no-pub --test-randomize-ordering-seed random

      - name: Upload golden test failures
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: golden-failures-${{ matrix.name }}
          path: ${{ matrix.dir }}/test/**/failures/
          if-no-files-found: ignore
